version: 5.0.3-{build}-{branch}
skip_tags: true
image: Visual Studio 2013
clone_depth: 1
environment:
  matrix:
  - GENERATOR: Visual Studio 12
  - GENERATOR: Visual Studio 12 Win64
build_script:
- cmd: >-
    cmake -G "%GENERATOR%" -Bbuild -H. -DCMAKE_INSTALL_PREFIX=./install

    cmake --build build --target install --config Release
artifacts:
- path: install/bin/HonokaMiku.exe