name: Test
on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Configure
      run: cmake -Bbuild -S. -DCMAKE_INSTALL_PREFIX=$PWD/install -DCMAKE_BUILD_TYPE=RelWithDebInfo
    - name: Build
      run: cmake --build build --target install
    - name: Chmod
      run: chmod 777 $PWD/install/bin/HonokaMiku
    - name: Test Program
      run: $PWD/install/bin/HonokaMiku -?
    - name: Check Version
      run: $PWD/install/bin/HonokaMiku -v
    - name: Artifact
      uses: actions/upload-artifact@v3
      with:
        name: HonokaMiku-linux-x86-64
        path: install
  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        platform: [Win32, x64, ARM64]
    defaults:
      run:
        shell: cmd
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Configure
      run: cmake -Bbuild -S. -A ${{ matrix.platform }} -DCMAKE_INSTALL_PREFIX=%CD%\install -DCOMPILE_PDB_OUTPUT_DIRECTORY=%CD%\install
    - name: Build
      shell: cmd
      run: cmake --build build --config RelWithDebInfo --target install
    - name: Test Program
      if: matrix.platform != 'ARM64'
      run: "%CD%\\install\\bin\\HonokaMiku -?"
    - name: Check Version
      if: matrix.platform != 'ARM64'
      run: "%CD%\\install\\bin\\HonokaMiku -v"
    - name: Artifact
      uses: actions/upload-artifact@v3
      with:
        name: HonokaMiku-windows-${{ matrix.platform }}
        path: install
  build-android:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        android-abi: [arm64-v8a, x86_64, armeabi-v7a, x86]
    steps:
    - name: Setup Android NDK r25b
      id: ndk
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r25b
        local-cache: true
    - name: Setup NDK Path
      run: echo "ANDROID_NDK_ROOT=${{ steps.ndk.outputs.ndk-path }}" >> $GITHUB_ENV
    - name: Checkout
      uses: actions/checkout@v3
    - name: Configure
      run: cmake -DCMAKE_SYSTEM_NAME=Android -DCMAKE_ANDROID_ARCH_ABI=${{ matrix.android-abi }} -DCMAKE_SYSTEM_VERSION=21 -Bbuild -S. -DCMAKE_INSTALL_PREFIX=%CD%\install -DCMAKE_BUILD_TYPE=RelWithDebInfo
    - name: Build
      run: cmake --build build --target install
    - name: Artifact
      uses: actions/upload-artifact@v3
      with:
        name: HonokaMiku-android-${{ matrix.android-abi }}
        path: install
